#ifndef __CONSOLE_SERVICE_H__
#define __SONSOLE_SERVICE_H__

enum console_service
{
    CONSOLE_GET_USER_INPUT,
    CONSOLE_GET_USER_INPUT_WITH_MSG,
    CONSOLE_GET_HIDDEN_USER_INPUT_WITH_MSG,
    CONSOLE_PUT_OUTPUT_MSG,
    CONSOLE_SERVICE_END
};

#define CONSOLE_SERVICE_CALL_BUFFER_COUNT          (CONSOLE_SERVICE_END)
#define CONSOLE_SERVICE_CALL_BUFFER                ((CONSOLE_SERVICE_END) - 1)

#endif